/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author laris
 */
public class TelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdm
     */
    public TelaAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CadastraUsuButton = new javax.swing.JButton();
        criarOsbutton = new javax.swing.JButton();
        EditaUsuButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        editarOsbutton = new javax.swing.JButton();
        listarOsbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrador");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        CadastraUsuButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CadastraUsuButton.setText("Cadastrar Usuário");
        CadastraUsuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraUsuButtonActionPerformed(evt);
            }
        });

        criarOsbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        criarOsbutton.setText("Criar Ordem de Serviço");
        criarOsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarOsbuttonActionPerformed(evt);
            }
        });

        EditaUsuButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EditaUsuButton3.setText("Editar Usuário");
        EditaUsuButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditaUsuButton3ActionPerformed(evt);
            }
        });

        editarOsbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editarOsbutton.setText("Editar Ordem de Serviço");
        editarOsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarOsbuttonActionPerformed(evt);
            }
        });

        listarOsbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listarOsbutton.setText("Listar Ordens de Serviço");
        listarOsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarOsbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarOsbutton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EditaUsuButton3)
                        .addGap(18, 18, 18)
                        .addComponent(CadastraUsuButton))
                    .addComponent(listarOsbutton)
                    .addComponent(criarOsbutton)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditaUsuButton3)
                    .addComponent(CadastraUsuButton))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(listarOsbutton)
                .addGap(19, 19, 19)
                .addComponent(criarOsbutton)
                .addGap(18, 18, 18)
                .addComponent(editarOsbutton)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastraUsuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraUsuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraUsuButtonActionPerformed

    private void criarOsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarOsbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criarOsbuttonActionPerformed

    private void EditaUsuButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditaUsuButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditaUsuButton3ActionPerformed

    private void editarOsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarOsbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarOsbuttonActionPerformed

    private void listarOsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarOsbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarOsbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastraUsuButton;
    private javax.swing.JButton EditaUsuButton3;
    private javax.swing.JButton criarOsbutton;
    private javax.swing.JButton editarOsbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton listarOsbutton;
    // End of variables declaration//GEN-END:variables
}
