/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author laris
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdm
     */
    public TelaPrincipal() {
        initComponents();
        editUserButton.setEnabled(false);
        CadastraUsuButton.setEnabled(false);
        EditarOsButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CadastraUsuButton = new javax.swing.JButton();
        criarOsButton = new javax.swing.JButton();
        editUserButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        EditarOsButton = new javax.swing.JButton();
        listarOsbutton = new javax.swing.JButton();
        labelPrincipal = new javax.swing.JLabel();
        labelConectado = new javax.swing.JLabel();
        sairButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        desktopPainel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        CadastraUsuButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CadastraUsuButton.setText("Cadastrar Usuário");
        CadastraUsuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraUsuButtonActionPerformed(evt);
            }
        });

        criarOsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        criarOsButton.setText("Criar O.S");
        criarOsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarOsButtonActionPerformed(evt);
            }
        });

        editUserButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editUserButton.setText("Editar Usuário");
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });

        EditarOsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EditarOsButton.setText("Editar O.S");
        EditarOsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarOsButtonActionPerformed(evt);
            }
        });

        listarOsbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listarOsbutton.setText("Listar O.S");
        listarOsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarOsbuttonActionPerformed(evt);
            }
        });

        labelPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelPrincipal.setText("Painel Principal");

        labelConectado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelConectado.setText("Conectado: ");

        sairButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sairButton.setText("SAIR");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desktopPainelLayout = new javax.swing.GroupLayout(desktopPainel);
        desktopPainel.setLayout(desktopPainelLayout);
        desktopPainelLayout.setHorizontalGroup(
            desktopPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPainelLayout.setVerticalGroup(
            desktopPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sairButton)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editUserButton)
                    .addComponent(CadastraUsuButton)
                    .addComponent(EditarOsButton)
                    .addComponent(listarOsbutton)
                    .addComponent(criarOsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelConectado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(desktopPainel)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelPrincipal)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelConectado)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(criarOsButton)
                        .addGap(18, 18, 18)
                        .addComponent(listarOsbutton)
                        .addGap(18, 18, 18)
                        .addComponent(EditarOsButton)
                        .addGap(18, 18, 18)
                        .addComponent(CadastraUsuButton)
                        .addGap(18, 18, 18)
                        .addComponent(editUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPainel)
                        .addGap(18, 18, 18)))
                .addComponent(sairButton)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastraUsuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraUsuButtonActionPerformed
        //Aqui sera implementado a tela de cadastro de usuarios dentro do desktoppainel
        TelaCadUsuario usuario = new TelaCadUsuario();
        usuario.setVisible(true);
        desktopPainel.add(usuario);
        
    }//GEN-LAST:event_CadastraUsuButtonActionPerformed

    private void criarOsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarOsButtonActionPerformed
        //Aqui sera implementado a tela de criar O.S dentro do desktop
        TelaCriarOs os = new TelaCriarOs();
        os.setVisible(true);
        desktopPainel.add(os);
        
    }//GEN-LAST:event_criarOsButtonActionPerformed

    private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserButtonActionPerformed
        // Aqui sera implementado a tela de editar usuarios dentro do desktop
        TelaEditarUser editar = new TelaEditarUser();
        editar.setVisible(true);
        desktopPainel.add(editar);
    }//GEN-LAST:event_editUserButtonActionPerformed

    private void EditarOsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarOsButtonActionPerformed
        // Aqui sera implementado a tela de editar OS dentro do desktop
    }//GEN-LAST:event_EditarOsButtonActionPerformed

    private void listarOsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarOsbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarOsbuttonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton CadastraUsuButton;
    public static javax.swing.JButton EditarOsButton;
    public static javax.swing.JButton criarOsButton;
    public static javax.swing.JDesktopPane desktopPainel;
    public static javax.swing.JButton editUserButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelConectado;
    private javax.swing.JLabel labelPrincipal;
    private javax.swing.JButton listarOsbutton;
    private javax.swing.JButton sairButton;
    public static javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

    private TelaCriarOs TelaCriarOs() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private TelaEditarUser TelaEditarUser() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
