/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import datal.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import objetos.OrdemServico;
import objetos.UsuarioDao;

/**
 *
 * @author Ronaldo Daniel
 */
public class TelaEditarOs extends javax.swing.JInternalFrame {
    
    public boolean validaOs(int id) {
        Connection conexao = null;
        
        String sql = "select * from tbOs where id=?";
        
        try {
            // Gera conexão e Statement
            conexao = new ModuloConexao().conector();
            PreparedStatement stmt = conexao.prepareStatement(sql);
            
            //CONSULTA BANCO DE DADOS E SUBSTITUI OS "?" PELO CONTEUDO SELECIONADO
            stmt.setString(1, String.valueOf(id));
            
            //EXECUTA AS INTRUÇÕES
            ResultSet rs = stmt.executeQuery();
            
            // verifica se o funcionario existe no banco de dados
            if (rs.next()){
                return true;
            }else{
                JOptionPane.showMessageDialog(null, "id inválido!");
                return false;
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
    
    public JComboBox pesquisaOs(JComboBox jComboBox) {
         
        try {
            // pega a conexão e o Statement
            Connection con = new ModuloConexao().conector();
            PreparedStatement stmt = con.prepareStatement("select * from tbOs");
            
            // executa um select
            ResultSet rs = stmt.executeQuery();
            
            // itera no ResultSet
            while (rs.next()) {
                // Recolhe os valores
                int id = rs.getInt("id");
                String veiculo = rs.getString("veiculo");
                String defeito = rs.getString("defeito");
                String servico = rs.getString("servico");
                
                // Junta os valores uma String
                String item = String.valueOf(id) + " " + veiculo + " " + defeito + " " + servico;
                
                // Salva no JComboBox
                jComboBox.addItem(item);
            }
            
            // Fecha tudo
            rs.close();
            stmt.close();
            con.close();
            
            return jComboBox;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Creates new form TelaEditarOs
     */
    public TelaEditarOs() {
        initComponents();
        pesquisaOs(listaOs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        valorServicoInput = new javax.swing.JTextField();
        veiculoInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EditarOsButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        listaOs = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        servicoInput = new javax.swing.JTextArea();
        idMecanicoInput = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        defeitoInput = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Ordem de Serviço");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Valor Serviço");

        valorServicoInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        valorServicoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorServicoInputActionPerformed(evt);
            }
        });

        veiculoInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        veiculoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoInputActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Veículo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Defeito");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Serviço");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Mecânico");

        EditarOsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EditarOsButton.setText("Editar");
        EditarOsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarOsButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Buscar OS");

        listaOs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listaOs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listaOsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                listaOsFocusLost(evt);
            }
        });
        listaOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaOsActionPerformed(evt);
            }
        });

        servicoInput.setColumns(20);
        servicoInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        servicoInput.setLineWrap(true);
        servicoInput.setRows(5);
        jScrollPane3.setViewportView(servicoInput);

        idMecanicoInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        defeitoInput.setColumns(20);
        defeitoInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        defeitoInput.setRows(5);
        jScrollPane1.setViewportView(defeitoInput);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditarOsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(veiculoInput)
                    .addComponent(valorServicoInput)
                    .addComponent(listaOs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(idMecanicoInput)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(listaOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valorServicoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(veiculoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idMecanicoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(EditarOsButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addContainerGap(376, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorServicoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorServicoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorServicoInputActionPerformed

    private void veiculoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoInputActionPerformed

    private void EditarOsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarOsButtonActionPerformed
        // TODO add your handling code here:
        // Recolhe todos os valores
        String valorServico = valorServicoInput.getText().strip();
        String veiculo = veiculoInput.getText().strip();
        String defeito = defeitoInput.getText().strip();
        String servico = servicoInput.getText().strip();
        int idMecanico = (int) idMecanicoInput.getValue();

        // Recolhe os valores da os selecionada
        int id = 0;
        String item = (String) listaOs.getSelectedItem();
        String[] listaItens = item.split(" ");

        // Verifica se todos os campos foram preenchidos

        boolean valido = false;
        if (valorServico.isBlank() || veiculo.isBlank() || defeito.isBlank() || servico.isBlank()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
            // converte todo o id passado para inteiro-
            id = Integer.parseInt(listaItens[0]);

            // Verifica se a os indicado existe na tabela
            valido = validaOs(id);
            System.out.println("id: " + id + " é valido");
        }

        // Salva no banco de dados se for valido
        if (valido) {

            OrdemServico os = new OrdemServico();

            // Passa todas os valores de ordem de serviço
            os.setVeiculo(veiculo);
            os.setDefeito(defeito);
            os.setServico(servico);
            os.setMecanico(idMecanico);
            os.setValorServico(valorServico);
            os.setOs(id);

            // Salva no banco de dados
            UsuarioDao dao = new UsuarioDao();
            dao.editarOs(os);
        }

    }//GEN-LAST:event_EditarOsButtonActionPerformed

    private void listaOsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaOsFocusGained
        // TODO add your handling code here:
        System.out.println("Estou em foco");
    }//GEN-LAST:event_listaOsFocusGained

    private void listaOsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaOsFocusLost
        // TODO add your handling code here:
        System.out.println("Estou fora de foco");
    }//GEN-LAST:event_listaOsFocusLost

    private void listaOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaOsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_listaOsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarOsButton;
    private javax.swing.JTextArea defeitoInput;
    private javax.swing.JSpinner idMecanicoInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> listaOs;
    private javax.swing.JTextArea servicoInput;
    private javax.swing.JTextField valorServicoInput;
    private javax.swing.JTextField veiculoInput;
    // End of variables declaration//GEN-END:variables
}
