/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import datal.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import objetos.OrdemServico;
import objetos.UsuarioDao;
import static telas.TelaPrincipal.desktopPainel;

/**
 *
 * @author Ronaldo Daniel
 */
public class TelaListarOs extends javax.swing.JInternalFrame {
    
    public List<OrdemServico> pesquisaOs() {
        try {
            // pega a conexão e o Statement
            Connection con = new ModuloConexao().conector();
            PreparedStatement stmt = con.prepareStatement("select * from tbOs");
            
            // executa um select
            ResultSet rs = stmt.executeQuery();
            
            // Gera a lista de Ordens de serviço
            List<OrdemServico> OSs = new ArrayList<>();
            
            // itera no ResultSet
            while (rs.next()) {
                // Cria o objeto Ordem de serviço
                OrdemServico os = new OrdemServico();
                os.setOs(rs.getInt("id"));
                os.setVeiculo(rs.getString("veiculo"));
                os.setDefeito(rs.getString("defeito"));
                os.setServico(rs.getString("servico"));
                os.setMecanico(rs.getInt("idMecanico"));
                os.setValorServico(rs.getString("valorServico"));
                os.setCliente(rs.getInt("idCliente"));
                
                // adicionando objeto a lista
                OSs.add(os);
            }
            
            rs.close();
            stmt.close();
            con.close();
            
            return OSs;
            
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Creates new form TelaListarOs
     */
    public TelaListarOs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        List<OrdemServico> oss = pesquisaOs();

        DefaultListModel<String> model = new  DefaultListModel<String>();
        listaOs = new javax.swing.JList<>(model);
        consultarOsButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        deletarButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listar Ordem de Serviço");

        for (int i=0; i < oss.size(); i++) {
            String id = String.valueOf(oss.get(i).getOs());
            String veiculo = oss.get(i).getVeiculo();
            String defeito = oss.get(i).getDefeito();
            model.addElement(id + " " + veiculo + " " + defeito);
        }
        jScrollPane1.setViewportView(listaOs);

        consultarOsButton.setText("Consultar");
        consultarOsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarOsButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");

        deletarButton.setText("Deletar");
        deletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deletarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultarOsButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(consultarOsButton)
                    .addComponent(deletarButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarOsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarOsButtonActionPerformed
        // TODO add your handling code here:
        String[] valor = listaOs.getSelectedValue().split(" ");
        System.out.println(valor[0]);
        
        TelaDadosOs listar = new TelaDadosOs(Integer.parseInt(valor[0]));
        this.dispose();
        listar.setVisible(true);
        desktopPainel.add(listar);
        
    }//GEN-LAST:event_consultarOsButtonActionPerformed

    private void deletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarButtonActionPerformed
        // TODO add your handling code here:
        String texto = listaOs.getSelectedValue();
        String[] valores = texto.split(" ");
        
        // Gera o objeto
        OrdemServico os = new OrdemServico();
        os.setOs(Integer.parseInt(valores[0]));
        
        // salva do banco de dados
        UsuarioDao dao = new UsuarioDao();
        dao.apagarOs(os);
    }//GEN-LAST:event_deletarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarOsButton;
    private javax.swing.JButton deletarButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaOs;
    // End of variables declaration//GEN-END:variables
}
